<?php
// This file does the initial database installation for the Havyaka Culture project
include_once 'includes/constants/sql_constants.php';

// Creates our SQL from a file generated by MySQL Workbench. This file is updated when we modify our database tables or structure.
$install_sql = file_get_contents('create_scripts.sql');

?>

<form method="get" action="<?php echo BASE;?>/install.php" name="install">
	<p>Install or reset the database:<br>
	<input type="submit" class="submit" name="cmd" value="install" /></p>
</form>

<form method="get" action="<?php echo BASE;?>/install.php" name="dummy_data">
	<p>Populate the database with dummy data:<br>
	<input type="submit" class="submit" name="cmd" value="dummy_data" /></p>
</form>

<?php
// Check for get data
if($_GET) {
	/* installs or resets the database to an empty state */
	if ($_GET['cmd'] == 'install') {
		$select = mysqli_select_db($link, DB_NAME);

		$install = mysqli_multi_query($link, $install_sql);
		if($install) {
			echo "<p>Database installed successfully<p>";
		}
		else {
			echo "<p>Database install failed.<p>";
		}
	}

	/* Adds dummy data to our database for testing purposes. */
	if ($_GET['cmd'] == 'dummy_data'){
		$table = array(LOCATION, COMMUNITY_TYPE, USERS, VENUE, EVENT_TYPE, EVENT_RECURRENCE, EVENT, CHEF,  FOOD, FOOD_CHEF_DETAILS, EVENT_PICTURE, USER_SAVED_INFO, ATTENDANCE);

		$select = mysqli_select_db($link, DB_NAME);
		$q = "INSERT INTO ".PSTORE. " (p_id,p_email,p_pass) VALUES(1,AES_ENCRYPT('connect.community.culture@gmail.com','ae4bca65f3283fe26a6d3b10b85c3a308'),AES_ENCRYPT('connectcommunity1','ae4bca65f3283fe26a6d3b10b85c3a308'));";

		$pstore_query = mysqli_query($link,$q);

		if($pstore_query) {
			echo "<p>pstore created successfully<p>";
		}
		else {
			echo "<p>" . $q . "</p>";
			echo "<p>pstore data install failed.<p>";
		}

		for ($i = 0; $i < count($table); $i++) {
			$name = $table[$i];
			/*
			SQL to load data from our CSV files. Example:
			LOAD DATA INFILE 'C:/wamp/www/havyaka_culture/dummy_data/user.csv'
			INTO TABLE user
			*/

 			$dummy_sql = "LOAD DATA INFILE '" . ROOT . "/dummy_data/$name.csv'
			INTO TABLE $name
			FIELDS TERMINATED BY ','
			OPTIONALLY ENCLOSED BY '\"'
			LINES TERMINATED BY '\\n';";
			
			$install = mysqli_query($link, $dummy_sql)  /*or die(mysql_error()) */;
			if($install) {
				echo "<p>Dummy data inserted into " . $table[$i] . " successfully<p>";
				if($name == 'community_connect_user') {
					$q_update = "update " .USERS. " set email= AES_ENCRYPT('calebc@iastate.edu','ae4bca65f3283fe26a6d3b10b85c3a308') where user_id =1;";
					$update_ex = mysqli_query($link,$q_update) or die(mysqli_error($link));
					$q_update = "update " .USERS. " set email= AES_ENCRYPT('nivi@iastate.edu','ae4bca65f3283fe26a6d3b10b85c3a308') where user_id =2;";
					$update_ex = mysqli_query($link,$q_update) or die(mysqli_error($link));
					$q_update = "update " .USERS. " set email= AES_ENCRYPT('jsinapov@iastate.edu','ae4bca65f3283fe26a6d3b10b85c3a308') where user_id =3;";
					$update_ex = mysqli_query($link,$q_update) or die(mysqli_error($link));
					$q_update = "update " .USERS. " set email= AES_ENCRYPT('arushi.gadde@gmail.com','ae4bca65f3283fe26a6d3b10b85c3a308') where user_id =4;";
					$update_ex = mysqli_query($link,$q_update) or die(mysqli_error($link));
					$q_update = "update " .USERS. " set email= AES_ENCRYPT('vighnesh.gadde@gmail.com','ae4bca65f3283fe26a6d3b10b85c3a308') where user_id =5;";
					$update_ex = mysqli_query($link,$q_update) or die(mysqli_error($link));
					$q_update = "update " .USERS. " set email= AES_ENCRYPT('pushpa.bhat@gmail.com','ae4bca65f3283fe26a6d3b10b85c3a308') where user_id =6;";
					$update_ex = mysqli_query($link,$q_update) or die(mysqli_error($link));
					$q_update = "update " .USERS. " set email= AES_ENCRYPT('savita.joshi@gmail.com','ae4bca65f3283fe26a6d3b10b85c3a308') where user_id =7;";
					$update_ex = mysqli_query($link,$q_update) or die(mysqli_error($link));
					$q_update = "update " .USERS. " set email= AES_ENCRYPT('arjun.gadde@gmail.com','ae4bca65f3283fe26a6d3b10b85c3a308') where user_id =8;";
					$update_ex = mysqli_query($link,$q_update) or die(mysqli_error($link));
				}
			}
			else {
				echo "<p>" . $dummy_sql . "</p>";
				echo "<p>Dummy data install failed.<p>";
			}
		}
	}
}

?>